### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by NextChocolate** [Dreace233/North-University-of-China-Rankings-Curriculum-Information#2]
1.课表配色有点不太美观，比较老气
2.课表显示不全
3.课表不能自定义背景图片以及设置透明度
4.不能手动添加课表
5.不能手动选择查看周数

**Comment by 123456789258** [comment]
希望成绩可以显示具体分数，只有优秀和良好很难统计。

**Comment by Dreace233** [comment]
> 希望成绩可以显示具体分数，只有优秀和良好很难统计。

这个是教务系统的限制，小程序是没有办法处理的
